version: '3.8'

services:
  # Site A - Alejandro's components (GC + PS)
  sitio-a:
    build: .
    container_name: sitio-a
    hostname: sitio-a
    networks:
      - biblioteca-network
    ports:
      - "5555:5555"  # GC REQ/REP
      - "5556:5556"  # GC PUB/SUB
    environment:
      - GC_BIND=tcp://0.0.0.0:5555
      - GC_PUB_BIND=tcp://0.0.0.0:5556
      - TOPIC_RENOVACION=RENOVACION
      - TOPIC_DEVOLUCION=DEVOLUCION
      - AP_REQ_CONNECT=tcp://sitio-b:5557
      - GC_MODE=serial
      - METRICS_CSV=metrics/results.csv
      - MEASUREMENT_WINDOW_SEC=120
    volumes:
      - ./data:/app/data
      - ./metrics:/app/metrics
    command: ["python", "-m", "gestor_central.server", "--mode", "serial", "--pretty"]
    depends_on:
      - sitio-b

  # Site B - Sebastián's components (Actores + GA)
  sitio-b:
    build: .
    container_name: sitio-b
    hostname: sitio-b
    networks:
      - biblioteca-network
    ports:
      - "5557:5557"  # AP REQ/REP
      - "5560:5560"  # GA_A
      - "5561:5561"  # GA_B
      - "5562:5562"  # GA_A Replication PUB
      - "5563:5563"  # GA_B Replication PUB
      - "5564:5564"  # GA Health REP
      - "5565:5565"  # GA Heartbeat PUB
    environment:
      - GC_PUB_CONNECT=tcp://sitio-a:5556
      - AP_REP_BIND=tcp://0.0.0.0:5557
      - GA_REP_BIND=tcp://0.0.0.0:5560
      - GA_HEALTH_REP_BIND=tcp://0.0.0.0:5564
      - GA_HEARTBEAT_PUB_BIND=tcp://0.0.0.0:5565
      - GA_HEARTBEAT_INTERVAL_MS=2000
      - GA_REPL_PUB_BIND=tcp://0.0.0.0:5562
      - GA_REPL_SUB_CONNECT=tcp://sitio-b:5563
      - GA_DATA_DIR=/app/data/siteA
      - BOOKS_FILE=books.json
      - LOANS_FILE=loans.json
      - OPLOG_FILE=oplog.json
      - APPLIED_INDEX_FILE=applied_index.json
      - SNAPSHOT_INTERVAL_OPS=500
    volumes:
      - ./data:/app/data
      - ./metrics:/app/metrics
    command: ["sh", "-c", "python -m actors.prestamo --pretty & python -m ga.server --data-dir /app/data/siteA --node-id A --pretty"]

  # Load Generator - Alejandro's PS clients
  load-generator:
    build: .
    container_name: load-generator
    hostname: load-generator
    networks:
      - biblioteca-network
    environment:
      - GC_ENDPOINT=tcp://sitio-a:5555
    volumes:
      - ./data:/app/data
      - ./metrics:/app/metrics
    command: ["python", "tools/spawn_ps.py", "--ps-per-site", "4", "--sites", "A,B", "--duration-sec", "120", "--gc", "tcp://sitio-a:5555", "--mode", "serial", "--out", "metrics/results.csv"]
    depends_on:
      - sitio-a
      - sitio-b

networks:
  biblioteca-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
